# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 07:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bearing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='condition/')),
                ('xws', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(max_length=512)),
                ('unique', models.BooleanField(default=False)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('maneuvers_energy', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Bearing')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'difficulties',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='factions/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrantsSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unique', models.BooleanField(default=False)),
                ('skill', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('skill_special_ruling', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_special_ruling', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='pilots/')),
                ('xws', models.CharField(max_length=255)),
                ('attack_override', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility_override', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hull_override', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shields_override', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('range', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^[1-5](-[1-5])?$')])),
                ('slug', models.SlugField(unique=True)),
                ('conditions', models.ManyToManyField(blank=True, to='xwingdata.Condition')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='PilotSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Pilot')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='reference-cards/')),
                ('text', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('attack', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hull', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shields', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('xws', models.CharField(max_length=255, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('energy', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('epic_points', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(unique=True)),
                ('actions', models.ManyToManyField(blank=True, to='xwingdata.Action')),
                ('faction', models.ManyToManyField(to='xwingdata.Faction')),
                ('maneuvers', models.ManyToManyField(through='xwingdata.Dial', to='xwingdata.Bearing')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, upload_to='sources/')),
                ('thumb', models.ImageField(blank=True, upload_to='sources/')),
                ('wave', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('special_wave_name', models.CharField(blank=True, max_length=255, null=True)),
                ('released', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^SWX[0-9]+$')])),
                ('announcement_date', models.DateField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('conditions', models.ManyToManyField(blank=True, to='xwingdata.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='SourcePilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Pilot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Ship')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=255)),
                ('slot_cost', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('points', models.IntegerField()),
                ('attack', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('range', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^[1-5](-[1-5])?$')])),
                ('text', models.CharField(max_length=512)),
                ('image', models.ImageField(blank=True, upload_to='upgrade/')),
                ('xws', models.CharField(max_length=255)),
                ('unique', models.BooleanField(default=False)),
                ('effect', models.CharField(blank=True, max_length=255)),
                ('limited', models.BooleanField(default=False)),
                ('energy', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('grants_attack', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('grants_agility', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('grants_hull', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('grants_shields', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('grants_skill', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('slug', models.SlugField(unique=True)),
                ('conditions', models.ManyToManyField(blank=True, to='xwingdata.Condition')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Faction')),
                ('grants_action', models.ManyToManyField(to='xwingdata.Action')),
                ('grants_slot', models.ManyToManyField(related_name='grants', through='xwingdata.GrantsSlot', to='xwingdata.Slot')),
                ('ship', models.ManyToManyField(blank=True, to='xwingdata.Ship')),
                ('size', models.ManyToManyField(blank=True, to='xwingdata.Size')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Slot')),
            ],
        ),
        migrations.AddField(
            model_name='sourceupgrade',
            name='upgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Upgrade'),
        ),
        migrations.AddField(
            model_name='source',
            name='pilots',
            field=models.ManyToManyField(through='xwingdata.SourcePilot', to='xwingdata.Pilot'),
        ),
        migrations.AddField(
            model_name='source',
            name='reference_cards',
            field=models.ManyToManyField(blank=True, to='xwingdata.ReferenceCard'),
        ),
        migrations.AddField(
            model_name='source',
            name='ships',
            field=models.ManyToManyField(through='xwingdata.SourceShip', to='xwingdata.Ship'),
        ),
        migrations.AddField(
            model_name='source',
            name='upgrades',
            field=models.ManyToManyField(through='xwingdata.SourceUpgrade', to='xwingdata.Upgrade'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='ship',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Size'),
        ),
        migrations.AlterUniqueTogether(
            name='referencecard',
            unique_together=set([('title', 'subtitle')]),
        ),
        migrations.AlterUniqueTogether(
            name='primaryfaction',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='pilotslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Slot'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Ship'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='slots',
            field=models.ManyToManyField(through='xwingdata.PilotSlot', to='xwingdata.Slot'),
        ),
        migrations.AddField(
            model_name='grantsslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Slot'),
        ),
        migrations.AddField(
            model_name='grantsslot',
            name='upgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Upgrade'),
        ),
        migrations.AddField(
            model_name='faction',
            name='primary_faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.PrimaryFaction'),
        ),
        migrations.AddField(
            model_name='dial',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Difficulty'),
        ),
        migrations.AddField(
            model_name='dial',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwingdata.Ship'),
        ),
        migrations.AlterUniqueTogether(
            name='upgrade',
            unique_together=set([('name', 'faction')]),
        ),
        migrations.AlterUniqueTogether(
            name='sourceupgrade',
            unique_together=set([('source', 'upgrade')]),
        ),
        migrations.AlterUniqueTogether(
            name='sourceship',
            unique_together=set([('source', 'ship')]),
        ),
        migrations.AlterUniqueTogether(
            name='sourcepilot',
            unique_together=set([('source', 'pilot')]),
        ),
        migrations.AlterUniqueTogether(
            name='ship',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='pilotslot',
            unique_together=set([('pilot', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='pilot',
            unique_together=set([('ship', 'faction', 'xws')]),
        ),
        migrations.AlterUniqueTogether(
            name='grantsslot',
            unique_together=set([('upgrade', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='faction',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='dial',
            unique_together=set([('ship', 'speed', 'bearing')]),
        ),
    ]
